version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: pg_isready -U postgres
      interval: 5s
  server:
    build:
        context: .
        dockerfile: server/Dockerfile
    working_dir: /code/server
    command:
      bash -c "python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      db:
        condition: service_healthy
  client:
    build:
        context: .
        dockerfile: client/Dockerfile
    command:
      bash -c "yarn install && yarn watch"
    working_dir: /code/client
    ports:
        - "8765:8765"
    volumes:
      - .:/code

volumes:
  postgres-data: