version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  server:
    build:
        context: .
        dockerfile: server/Dockerfile
    working_dir: /code/server
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db
  client:
    build:
        context: .
        dockerfile: client/Dockerfile
    command: yarn watch
    working_dir: /code/client
    ports:
        - "8765:8765"
    volumes:
      - ./client/dist:/code/client/dist